version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres_bd"
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"